use_frameworks!

platform :ios, '10.0'

target 'XMultiTabModule-iOS_Example' do
  pod 'XMultiTabModule-iOS', :path => '../'

  target 'XMultiTabModule-iOS_Tests' do
    inherit! :search_paths

    
  end
end
